/**
 * reportGenerator — assembles a PDF station report.
 *
 * Strategy:
 *   1. Load the INMACOM logo (Image element — avoids fetch() extension issues).
 *   2. Build the A4 header: logo (natural aspect) + station name + reporter info.
 *   3. Capture the station-report-content DOM with html2canvas, ignoring any
 *      element with data-report-exclude="true" (header buttons, recent
 *      measurements card, visible historical-data card, etc.). Slice the
 *      capture into A4-sized pages.
 *   4. For each chart image from StationCharts.captureCharts(), draw a title
 *      and embed the PNG, page-breaking when needed.
 *   5. Add footers on all pages and save the PDF.
 */

import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import type { ChartImage } from '@/Components/Stations/StationCharts';

export type { ChartImage };

export interface ReportUser {
    display_name: string;
    email: string;
    role: string;
}

export interface ReportStation {
    code: string;
    name: string;
    country?: string | null;
    category: string;
    water_source: string;
}

const LOGO_PATH = '/images/inmacom-logo.png';

/**
 * Loads an image URL as a base-64 data URL and its natural pixel dimensions.
 * Uses an Image element + canvas to bypass fetch() (which can be intercepted
 * by browser extensions causing ERR_FAILED 200 OK).
 */
async function loadImage(src: string): Promise<{ dataUrl: string; width: number; height: number } | null> {
    return new Promise((resolve) => {
        const img = new Image();
        img.onload = () => {
            try {
                const canvas = document.createElement('canvas');
                canvas.width = img.naturalWidth;
                canvas.height = img.naturalHeight;
                const ctx = canvas.getContext('2d');
                if (!ctx) { resolve(null); return; }
                ctx.drawImage(img, 0, 0);
                resolve({
                    dataUrl: canvas.toDataURL('image/png'),
                    width:   img.naturalWidth,
                    height:  img.naturalHeight,
                });
            } catch {
                resolve(null);
            }
        };
        img.onerror = () => resolve(null);
        img.src = src;
    });
}

/**
 * Main export — generates and downloads a PDF for the given station.
 *
 * @param station       Station metadata shown in the header.
 * @param user          Logged-in user shown as the "generated by" field.
 * @param chartImages   Array of { title, dataUrl } from StationCharts.captureCharts().
 * @param elementId     id of the DOM element whose content is embedded in the PDF.
 *                      Elements with data-report-exclude="true" are skipped.
 * @param onProgress    Optional callback fired with 0–100 progress value.
 */
export async function generateStationReport(
    station: ReportStation,
    user: ReportUser,
    chartImages: ChartImage[],
    elementId = 'station-report-content',
    onProgress?: (pct: number) => void,
): Promise<void> {
    onProgress?.(5);

    // ── Set up jsPDF ──────────────────────────────────────────────────────────
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

    const PAGE_W  = pdf.internal.pageSize.getWidth();   // 210 mm
    const PAGE_H  = pdf.internal.pageSize.getHeight();  // 297 mm
    const MARGIN  = 12; // mm
    const CONTENT_W = PAGE_W - MARGIN * 2;
    const FOOTER_H  = 10; // reserved at bottom of every page

    // ── Load logo (preserve natural aspect ratio) ─────────────────────────────
    const logo = await loadImage(LOGO_PATH);
    onProgress?.(12);

    const generatedDate = new Date().toLocaleDateString(undefined, {
        year: 'numeric', month: 'long', day: 'numeric',
    });

    // ── Draw header on first page ─────────────────────────────────────────────
    let cursorY = MARGIN;

    const LOGO_MAX_H = 16; // mm
    let logoW = 0;
    let logoH = 0;
    if (logo) {
        const aspect = logo.width / logo.height;
        logoH = LOGO_MAX_H;
        logoW = LOGO_MAX_H * aspect;
        try {
            pdf.addImage(logo.dataUrl, 'PNG', MARGIN, cursorY, logoW, logoH);
        } catch { /* ignore */ }
    }

    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(30, 30, 30);
    pdf.text(station.name, PAGE_W - MARGIN, cursorY + 6, { align: 'right' });

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100, 100, 100);
    pdf.text(
        `${station.code} · ${station.category} · ${station.country ?? ''}`.replace(/ · $/, ''),
        PAGE_W - MARGIN,
        cursorY + 12,
        { align: 'right' },
    );

    cursorY += Math.max(logoH, 16) + 6;

    pdf.setDrawColor(220, 220, 220);
    pdf.line(MARGIN, cursorY, PAGE_W - MARGIN, cursorY);
    cursorY += 5;

    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(80, 80, 80);
    pdf.text(`Generated by: ${user.display_name} (${user.email}) · Role: ${user.role}`, MARGIN, cursorY);
    cursorY += 5;
    pdf.text(`Generated on: ${generatedDate}`, MARGIN, cursorY);
    cursorY += 8;

    // ── Capture station page content ──────────────────────────────────────────
    const pageEl = document.getElementById(elementId);
    if (pageEl) {
        // Briefly let the layout settle
        await new Promise((r) => setTimeout(r, 200));

        const pageCanvas = await html2canvas(pageEl, {
            scale: 2,
            useCORS: true,
            logging: false,
            backgroundColor: '#ffffff',
            scrollX: 0,
            scrollY: -window.scrollY,
            ignoreElements: (el) =>
                el instanceof HTMLElement && el.dataset.reportExclude === 'true',
        });
        onProgress?.(35);

        // Scale entire capture to content width and slice across pages
        const imgW = CONTENT_W;
        const imgH = (pageCanvas.height / pageCanvas.width) * imgW;
        const pxPerMm = pageCanvas.width / imgW;

        let srcY = 0;
        let firstPage = true;
        while (srcY < pageCanvas.height) {
            const usableH = (firstPage ? PAGE_H - cursorY - FOOTER_H : PAGE_H - MARGIN - FOOTER_H);
            const sliceMmH = Math.min(usableH, imgH - srcY / pxPerMm);
            const slicePxH = Math.min(sliceMmH * pxPerMm, pageCanvas.height - srcY);

            const sliceCanvas = document.createElement('canvas');
            sliceCanvas.width = pageCanvas.width;
            sliceCanvas.height = slicePxH;
            const ctx = sliceCanvas.getContext('2d')!;
            ctx.fillStyle = '#ffffff';
            ctx.fillRect(0, 0, sliceCanvas.width, sliceCanvas.height);
            ctx.drawImage(pageCanvas, 0, -srcY);

            const sliceData = sliceCanvas.toDataURL('image/jpeg', 0.92);
            pdf.addImage(sliceData, 'JPEG', MARGIN, firstPage ? cursorY : MARGIN, imgW, slicePxH / pxPerMm);

            srcY += slicePxH;
            if (srcY < pageCanvas.height) {
                pdf.addPage();
                firstPage = false;
            } else {
                cursorY = (firstPage ? cursorY : MARGIN) + slicePxH / pxPerMm + 8;
                firstPage = false;
            }
        }
        onProgress?.(60);
    }

    // ── Embed each chart image ────────────────────────────────────────────────
    const totalCharts = chartImages.length;
    for (let idx = 0; idx < totalCharts; idx++) {
        const { title, dataUrl } = chartImages[idx];

        const imgDims = await getImageDimensions(dataUrl);
        const imgAspect = imgDims ? imgDims.height / imgDims.width : 0.4;
        const imgH = CONTENT_W * imgAspect;

        const sectionH = 8 + imgH;

        if (cursorY + sectionH > PAGE_H - FOOTER_H) {
            pdf.addPage();
            cursorY = MARGIN;
        }

        // Section title
        pdf.setFontSize(11);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(40, 40, 40);
        pdf.text(title, MARGIN, cursorY);
        cursorY += 6;

        try {
            pdf.addImage(dataUrl, 'PNG', MARGIN, cursorY, CONTENT_W, imgH);
        } catch { /* skip corrupt image */ }
        cursorY += imgH + 8;

        onProgress?.(60 + Math.round((idx + 1) / totalCharts * 35));
    }

    // ── Footers on all pages ──────────────────────────────────────────────────
    const totalPages = pdf.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        pdf.setPage(i);
        pdf.setFontSize(8);
        pdf.setFont('helvetica', 'italic');
        pdf.setTextColor(150, 150, 150);
        pdf.text('INMACOM MIS — Confidential', MARGIN, PAGE_H - 5);
        pdf.text(`Page ${i} / ${totalPages}`, PAGE_W - MARGIN, PAGE_H - 5, { align: 'right' });
    }

    // ── Save ──────────────────────────────────────────────────────────────────
    const filename = `station-${station.code}-report-${new Date().toISOString().slice(0, 10)}.pdf`;
    pdf.save(filename);
    onProgress?.(100);
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Returns the natural dimensions of an image data URL without creating a visible element. */
function getImageDimensions(dataUrl: string): Promise<{ width: number; height: number } | null> {
    return new Promise((resolve) => {
        const img = new Image();
        img.onload = () => resolve({ width: img.naturalWidth, height: img.naturalHeight });
        img.onerror = () => resolve(null);
        img.src = dataUrl;
    });
}
